// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllowICMPPing() {
  return window['go']['main']['App']['AllowICMPPing']();
}

export function AnalyzeOfflineEvtx(arg1) {
  return window['go']['main']['App']['AnalyzeOfflineEvtx'](arg1);
}

export function ApplyAdvancedDebloat(arg1) {
  return window['go']['main']['App']['ApplyAdvancedDebloat'](arg1);
}

export function ApplyNativeAction(arg1, arg2) {
  return window['go']['main']['App']['ApplyNativeAction'](arg1, arg2);
}

export function ApplyNativeNetworkConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ApplyNativeNetworkConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function ApplyNativeSecurity(arg1, arg2) {
  return window['go']['main']['App']['ApplyNativeSecurity'](arg1, arg2);
}

export function ApplyNetworkConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ApplyNetworkConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function ApplyPerfTweak(arg1, arg2) {
  return window['go']['main']['App']['ApplyPerfTweak'](arg1, arg2);
}

export function ApplySecurity(arg1, arg2) {
  return window['go']['main']['App']['ApplySecurity'](arg1, arg2);
}

export function ClearStandbyMemory() {
  return window['go']['main']['App']['ClearStandbyMemory']();
}

export function CollectForensics(arg1) {
  return window['go']['main']['App']['CollectForensics'](arg1);
}

export function ConfigurePageFile(arg1, arg2) {
  return window['go']['main']['App']['ConfigurePageFile'](arg1, arg2);
}

export function DeepRemoveSoftware(arg1) {
  return window['go']['main']['App']['DeepRemoveSoftware'](arg1);
}

export function DeepRemoveSoftwareNative(arg1) {
  return window['go']['main']['App']['DeepRemoveSoftwareNative'](arg1);
}

export function EmailReport(arg1, arg2) {
  return window['go']['main']['App']['EmailReport'](arg1, arg2);
}

export function ExecuteDevAction(arg1) {
  return window['go']['main']['App']['ExecuteDevAction'](arg1);
}

export function ExportSystemReport() {
  return window['go']['main']['App']['ExportSystemReport']();
}

export function FlushDNS() {
  return window['go']['main']['App']['FlushDNS']();
}

export function GenerateAIPrompt(arg1) {
  return window['go']['main']['App']['GenerateAIPrompt'](arg1);
}

export function GetAllProcesses() {
  return window['go']['main']['App']['GetAllProcesses']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAppVersionNative() {
  return window['go']['main']['App']['GetAppVersionNative']();
}

export function GetAudit() {
  return window['go']['main']['App']['GetAudit']();
}

export function GetBootAnalysis() {
  return window['go']['main']['App']['GetBootAnalysis']();
}

export function GetBrowserStatus() {
  return window['go']['main']['App']['GetBrowserStatus']();
}

export function GetCachedAudit() {
  return window['go']['main']['App']['GetCachedAudit']();
}

export function GetCurrentPowerPlan() {
  return window['go']['main']['App']['GetCurrentPowerPlan']();
}

export function GetDashboardStatus() {
  return window['go']['main']['App']['GetDashboardStatus']();
}

export function GetDetailedSystemLogs() {
  return window['go']['main']['App']['GetDetailedSystemLogs']();
}

export function GetDriverHealth() {
  return window['go']['main']['App']['GetDriverHealth']();
}

export function GetInstalledSoftwareStatus() {
  return window['go']['main']['App']['GetInstalledSoftwareStatus']();
}

export function GetInstalledSoftwareStatusNative() {
  return window['go']['main']['App']['GetInstalledSoftwareStatusNative']();
}

export function GetInstallerCatalog() {
  return window['go']['main']['App']['GetInstallerCatalog']();
}

export function GetLastRCAResult() {
  return window['go']['main']['App']['GetLastRCAResult']();
}

export function GetNativeAudit() {
  return window['go']['main']['App']['GetNativeAudit']();
}

export function GetNativeInstallerCatalog() {
  return window['go']['main']['App']['GetNativeInstallerCatalog']();
}

export function GetNativeSetupStatus() {
  return window['go']['main']['App']['GetNativeSetupStatus']();
}

export function GetNativeStats() {
  return window['go']['main']['App']['GetNativeStats']();
}

export function GetPerformanceStatus() {
  return window['go']['main']['App']['GetPerformanceStatus']();
}

export function GetProductKeys() {
  return window['go']['main']['App']['GetProductKeys']();
}

export function GetRDPStatus() {
  return window['go']['main']['App']['GetRDPStatus']();
}

export function GetSecurityCenterStatus() {
  return window['go']['main']['App']['GetSecurityCenterStatus']();
}

export function GetSetupStatus() {
  return window['go']['main']['App']['GetSetupStatus']();
}

export function GetStartupApps() {
  return window['go']['main']['App']['GetStartupApps']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetSystemHealth() {
  return window['go']['main']['App']['GetSystemHealth']();
}

export function GetUSBStatus() {
  return window['go']['main']['App']['GetUSBStatus']();
}

export function GetWindowsServiceStatus() {
  return window['go']['main']['App']['GetWindowsServiceStatus']();
}

export function HasAdminPassword() {
  return window['go']['main']['App']['HasAdminPassword']();
}

export function HibernateHeavyApps() {
  return window['go']['main']['App']['HibernateHeavyApps']();
}

export function InstallBulkNative(arg1) {
  return window['go']['main']['App']['InstallBulkNative'](arg1);
}

export function InstallGlobalRamOptimizer(arg1) {
  return window['go']['main']['App']['InstallGlobalRamOptimizer'](arg1);
}

export function InstallSoftware(arg1) {
  return window['go']['main']['App']['InstallSoftware'](arg1);
}

export function InstallSoftwareNative(arg1) {
  return window['go']['main']['App']['InstallSoftwareNative'](arg1);
}

export function InstallStartupCleanup(arg1) {
  return window['go']['main']['App']['InstallStartupCleanup'](arg1);
}

export function InstallWindowsService(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['InstallWindowsService'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function KillProcess(arg1) {
  return window['go']['main']['App']['KillProcess'](arg1);
}

export function OpenOutputFolder(arg1) {
  return window['go']['main']['App']['OpenOutputFolder'](arg1);
}

export function PauseWindowsUpdate(arg1) {
  return window['go']['main']['App']['PauseWindowsUpdate'](arg1);
}

export function PerformSilentAudit() {
  return window['go']['main']['App']['PerformSilentAudit']();
}

export function Ping(arg1) {
  return window['go']['main']['App']['Ping'](arg1);
}

export function PingHost(arg1) {
  return window['go']['main']['App']['PingHost'](arg1);
}

export function RefreshAudit() {
  return window['go']['main']['App']['RefreshAudit']();
}

export function RenewIP() {
  return window['go']['main']['App']['RenewIP']();
}

export function ResetAdminPassword() {
  return window['go']['main']['App']['ResetAdminPassword']();
}

export function RestoreAnimations() {
  return window['go']['main']['App']['RestoreAnimations']();
}

export function RestoreBackgroundApps() {
  return window['go']['main']['App']['RestoreBackgroundApps']();
}

export function RunAdvancedClean(arg1) {
  return window['go']['main']['App']['RunAdvancedClean'](arg1);
}

export function RunAdvancedCleanup(arg1) {
  return window['go']['main']['App']['RunAdvancedCleanup'](arg1);
}

export function RunCleanup(arg1) {
  return window['go']['main']['App']['RunCleanup'](arg1);
}

export function RunNativeAction(arg1, arg2) {
  return window['go']['main']['App']['RunNativeAction'](arg1, arg2);
}

export function RunNativeCleanup(arg1) {
  return window['go']['main']['App']['RunNativeCleanup'](arg1);
}

export function ScanAdvancedCleanup(arg1) {
  return window['go']['main']['App']['ScanAdvancedCleanup'](arg1);
}

export function ScanNativeCleanup(arg1) {
  return window['go']['main']['App']['ScanNativeCleanup'](arg1);
}

export function ScheduleAutoCleanup(arg1) {
  return window['go']['main']['App']['ScheduleAutoCleanup'](arg1);
}

export function SecurityCenterAction(arg1) {
  return window['go']['main']['App']['SecurityCenterAction'](arg1);
}

export function SelectEvtxFile() {
  return window['go']['main']['App']['SelectEvtxFile']();
}

export function SelectWallpaperFile() {
  return window['go']['main']['App']['SelectWallpaperFile']();
}

export function SendWebhookAlert(arg1, arg2) {
  return window['go']['main']['App']['SendWebhookAlert'](arg1, arg2);
}

export function SetAdminPassword(arg1, arg2) {
  return window['go']['main']['App']['SetAdminPassword'](arg1, arg2);
}

export function SetAnimations(arg1) {
  return window['go']['main']['App']['SetAnimations'](arg1);
}

export function SetBackgroundApps(arg1) {
  return window['go']['main']['App']['SetBackgroundApps'](arg1);
}

export function SetDefaultWallpaper() {
  return window['go']['main']['App']['SetDefaultWallpaper']();
}

export function SetDesktopWallpaper(arg1) {
  return window['go']['main']['App']['SetDesktopWallpaper'](arg1);
}

export function SetPageFile(arg1, arg2) {
  return window['go']['main']['App']['SetPageFile'](arg1, arg2);
}

export function SetPowerPlan(arg1) {
  return window['go']['main']['App']['SetPowerPlan'](arg1);
}

export function SetStartupApp(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetStartupApp'](arg1, arg2, arg3);
}

export function SetWallpaper(arg1) {
  return window['go']['main']['App']['SetWallpaper'](arg1);
}

export function StopInstall() {
  return window['go']['main']['App']['StopInstall']();
}

export function TCPIPReset() {
  return window['go']['main']['App']['TCPIPReset']();
}

export function TestRamOptimizer() {
  return window['go']['main']['App']['TestRamOptimizer']();
}

export function ToggleAnimations(arg1) {
  return window['go']['main']['App']['ToggleAnimations'](arg1);
}

export function ToggleBackgroundApps(arg1) {
  return window['go']['main']['App']['ToggleBackgroundApps'](arg1);
}

export function ToggleStartupApp(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleStartupApp'](arg1, arg2, arg3);
}

export function TrimProcessWorkingSets() {
  return window['go']['main']['App']['TrimProcessWorkingSets']();
}

export function UninstallSoftware(arg1) {
  return window['go']['main']['App']['UninstallSoftware'](arg1);
}

export function UninstallSoftwareNative(arg1) {
  return window['go']['main']['App']['UninstallSoftwareNative'](arg1);
}

export function UninstallWindowsService() {
  return window['go']['main']['App']['UninstallWindowsService']();
}

export function UploadAuditData(arg1) {
  return window['go']['main']['App']['UploadAuditData'](arg1);
}

export function VerifyAdminPassword(arg1) {
  return window['go']['main']['App']['VerifyAdminPassword'](arg1);
}

export function WinsockReset() {
  return window['go']['main']['App']['WinsockReset']();
}
