// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AllowICMPPing():Promise<string>;

export function AnalyzeOfflineEvtx(arg1:string):Promise<main.RCAResult>;

export function ApplyAdvancedDebloat(arg1:main.DebloatConfig):Promise<string>;

export function ApplyNativeAction(arg1:string,arg2:Array<string>):Promise<string>;

export function ApplyNativeNetworkConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function ApplyNativeSecurity(arg1:string,arg2:string):Promise<string>;

export function ApplyNetworkConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function ApplyPerfTweak(arg1:string,arg2:boolean):Promise<string>;

export function ApplySecurity(arg1:string,arg2:string):Promise<string>;

export function ClearStandbyMemory():Promise<string>;

export function CollectForensics(arg1:main.ForensicsConfig):Promise<main.ForensicsResult>;

export function ConfigurePageFile(arg1:number,arg2:number):Promise<string>;

export function DeepRemoveSoftware(arg1:string):Promise<string>;

export function DeepRemoveSoftwareNative(arg1:string):Promise<string>;

export function EmailReport(arg1:main.SmtpConfig,arg2:string):Promise<string>;

export function ExecuteDevAction(arg1:string):Promise<string>;

export function ExportSystemReport():Promise<string>;

export function FlushDNS():Promise<string>;

export function GenerateAIPrompt(arg1:main.RCAResult):Promise<string>;

export function GetAllProcesses():Promise<Array<main.ProcessInfo>>;

export function GetAppVersion():Promise<string>;

export function GetAppVersionNative():Promise<string>;

export function GetAudit():Promise<main.AuditData>;

export function GetBootAnalysis():Promise<Array<main.BootItem>>;

export function GetBrowserStatus():Promise<string>;

export function GetCachedAudit():Promise<string>;

export function GetCurrentPowerPlan():Promise<string>;

export function GetDashboardStatus():Promise<main.DashboardStatus>;

export function GetDetailedSystemLogs():Promise<Array<main.HealthLog>>;

export function GetDriverHealth():Promise<Array<main.DriverInfo>>;

export function GetInstalledSoftwareStatus():Promise<Record<string, boolean>>;

export function GetInstalledSoftwareStatusNative():Promise<Record<string, boolean>>;

export function GetInstallerCatalog():Promise<Array<main.SoftwareItem>>;

export function GetLastRCAResult():Promise<main.RCAResult>;

export function GetNativeAudit():Promise<main.AuditData>;

export function GetNativeInstallerCatalog():Promise<Array<main.SoftwareItem>>;

export function GetNativeSetupStatus():Promise<Record<string, string>>;

export function GetNativeStats():Promise<main.StatsData>;

export function GetPerformanceStatus():Promise<main.PerformanceStatus>;

export function GetProductKeys():Promise<string>;

export function GetRDPStatus():Promise<string>;

export function GetSecurityCenterStatus():Promise<main.SecurityCenterStatus>;

export function GetSetupStatus():Promise<Record<string, string>>;

export function GetStartupApps():Promise<Array<main.StartupApp>>;

export function GetStats():Promise<main.StatsData>;

export function GetSystemHealth():Promise<main.SystemHealth>;

export function GetUSBStatus():Promise<string>;

export function GetWindowsServiceStatus():Promise<string>;

export function HasAdminPassword():Promise<boolean>;

export function HibernateHeavyApps():Promise<string>;

export function InstallBulkNative(arg1:Array<string>):Promise<string>;

export function InstallGlobalRamOptimizer(arg1:boolean):Promise<string>;

export function InstallSoftware(arg1:string):Promise<string>;

export function InstallSoftwareNative(arg1:string):Promise<string>;

export function InstallStartupCleanup(arg1:boolean):Promise<string>;

export function InstallWindowsService(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function KillProcess(arg1:number):Promise<string>;

export function OpenOutputFolder(arg1:string):Promise<void>;

export function PauseWindowsUpdate(arg1:number):Promise<string>;

export function PerformSilentAudit():Promise<void>;

export function Ping(arg1:string):Promise<string>;

export function PingHost(arg1:string):Promise<string>;

export function RefreshAudit():Promise<void>;

export function RenewIP():Promise<string>;

export function ResetAdminPassword():Promise<string>;

export function RestoreAnimations():Promise<string>;

export function RestoreBackgroundApps():Promise<string>;

export function RunAdvancedClean(arg1:string):Promise<string>;

export function RunAdvancedCleanup(arg1:string):Promise<string>;

export function RunCleanup(arg1:string):Promise<string>;

export function RunNativeAction(arg1:string,arg2:Array<string>):Promise<string>;

export function RunNativeCleanup(arg1:string):Promise<string>;

export function ScanAdvancedCleanup(arg1:string):Promise<string>;

export function ScanNativeCleanup(arg1:string):Promise<string>;

export function ScheduleAutoCleanup(arg1:number):Promise<string>;

export function SecurityCenterAction(arg1:string):Promise<string>;

export function SelectEvtxFile():Promise<string>;

export function SelectWallpaperFile():Promise<string>;

export function SendWebhookAlert(arg1:string,arg2:string):Promise<string>;

export function SetAdminPassword(arg1:string,arg2:string):Promise<string>;

export function SetAnimations(arg1:boolean):Promise<string>;

export function SetBackgroundApps(arg1:boolean):Promise<string>;

export function SetDefaultWallpaper():Promise<string>;

export function SetDesktopWallpaper(arg1:string):Promise<string>;

export function SetPageFile(arg1:number,arg2:number):Promise<string>;

export function SetPowerPlan(arg1:string):Promise<string>;

export function SetStartupApp(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function SetWallpaper(arg1:string):Promise<string>;

export function StopInstall():Promise<void>;

export function TCPIPReset():Promise<string>;

export function TestRamOptimizer():Promise<string>;

export function ToggleAnimations(arg1:boolean):Promise<string>;

export function ToggleBackgroundApps(arg1:boolean):Promise<string>;

export function ToggleStartupApp(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function TrimProcessWorkingSets():Promise<string>;

export function UninstallSoftware(arg1:string):Promise<string>;

export function UninstallSoftwareNative(arg1:string):Promise<string>;

export function UninstallWindowsService():Promise<string>;

export function UploadAuditData(arg1:Record<string, any>):Promise<string>;

export function VerifyAdminPassword(arg1:string):Promise<boolean>;

export function WinsockReset():Promise<string>;
